GET http://localhost:5000/product/3

###
GET http://localhost:5000/product/*/7/0


###
POST http://localhost:5000/product
content-type: application/json

{
    "name": "lem kertas",
    "price": 4500
}

###
PATCH  http://localhost:5000/product/3
content-type: application/json

{
    "name": "pencil update",
    "price": 1400
}

###
DELETE http://localhost:5000/product/5